// examples/05-react-embed/src/ZettaCheckout.tsx
import { useEffect, useRef } from "react";

type Props = {
  merchantId: string;
  amount: string;
  currency?: string;
  reference?: string;
  onSettled?: (detail: { intentId: string; signature: string }) => void;
};

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "zetta-checkout": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement> & {
          "data-merchant-id"?: string;
          "data-amount"?: string;
          "data-currency"?: string;
          "data-reference"?: string;
        },
        HTMLElement
      >;
    }
  }
}

export function ZettaCheckout({ merchantId, amount, currency = "USD", reference, onSettled }: Props) {
  const ref = useRef<HTMLElement | null>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onSettled) return;
    const handler = (e: Event) => onSettled((e as CustomEvent).detail);
    el.addEventListener("zettapay:settled", handler);
    return () => el.removeEventListener("zettapay:settled", handler);
  }, [onSettled]);

  return (
    <zetta-checkout
      ref={ref as React.Ref<HTMLElement>}
      data-merchant-id={merchantId}
      data-amount={amount}
      data-currency={currency}
      data-reference={reference}
    />
  );
}

// examples/06-vue-embed/src/ZettaCheckout.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";

const props = defineProps<{
  merchantId: string;
  amount: string;
  currency?: string;
  reference?: string;
}>();
const emit = defineEmits<{ settled: [{ intentId: string; signature: string }] }>();

const el = ref<HTMLElement | null>(null);

function onSettled(event: Event) {
  emit("settled", (event as CustomEvent).detail);
}

onMounted(() => el.value?.addEventListener("zettapay:settled", onSettled));
onBeforeUnmount(() => el.value?.removeEventListener("zettapay:settled", onSettled));
</script>

<template>
  <zetta-checkout
    ref="el"
    :data-merchant-id="props.merchantId"
    :data-amount="props.amount"
    :data-currency="props.currency ?? 'USD'"
    :data-reference="props.reference"
  />
</template>
